name: point_of_sale
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.5.0

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter_custom_clippers: ^2.0.0
  #appbar_textfield: ^1.0.1+1
  awesome_dropdown: ^0.0.4
  blue_thermal_printer: ^1.1.4
  cached_network_image: ^2.5.1
  carousel_slider: ^4.0.0
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.2
  data_connection_checker: ^0.3.4
  date_time_picker: ^2.1.0
  easy_localization: ^2.3.3+1
  equatable: ^2.0.3
  esc_pos_printer: ^4.0.3
  esc_pos_utils: ^1.0.0
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^1.0.1
  flutter_bloc: ^7.0.1
  flutter_pagewise: ^2.0.1
  flutter_search_bar: ^2.1.0
  flutter_session: ^0.1.1
  flutter_slidable: ^1.2.0
  flutter_sunmi_printer: ^0.2.1
  flutter_switch: ^0.3.2
  fluttertoast: ^8.0.8
  http: ^0.13.3
  image: ^2.1.19
  image_picker: ^0.6.6+5
  intl: ^0.17.0
  network_to_file_image: ^4.0.1
  path: ^1.8.0
  path_provider: ^1.6.28
  ping_discover_network: ^0.2.0+1
  rename: ^1.3.1
  shared_preferences: ^0.5.12+4
  sqflite: ^2.0.0+3
  utf: ^0.9.0+5
  jwt_decode: ^0.2.0
  json_annotation: ^3.1.1
  awesome_dialog: ^2.2.1
  collection: ^1.15.0
  modal_bottom_sheet: ^2.0.1
  dropdown_button2: ^1.9.2
  number_inc_dec: ^0.8.0
  another_flutter_splash_screen: ^1.0.2
  aligned_dialog: ^0.0.6
  get: ^4.6.5
  foundation_flutter:
dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^3.3.0
  flutter_launcher_icons: "^0.8.0"
  flutter_test:
    sdk: flutter
# ---------
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.jpg"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/app_icon.jpg"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/
    - assets/gif/
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: Moul
      fonts:
        - asset: assets/fonts/Moul-Regular.ttf
    - family: Content
      fonts:
        - asset: assets/fonts/Content-Regular.ttf
    - family: battambang
      fonts:
        - asset: assets/fonts/khmer_os_battambang.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
